name: TQQQ Daily Signal

on:
  schedule:
    - cron: "0 22 * * 1-5"   # every weekday at 10pm UTC
  workflow_dispatch:         # allows manual trigger

jobs:
  run-signal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yfinance scikit-learn joblib pandas numpy

      - name: Run trading signal
        run: python tqqq_signal.py


  
