name: Daily TQQQ Signal

on:
  schedule:
    - cron: "30 13 * * 1-5"   # Run at 9:30 AM EST (13:30 UTC) weekdays
  workflow_dispatch:           # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install yfinance scikit-learn joblib gspread oauth2client pandas numpy

    - name: Run TQQQ Signal
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        python tqqq_signal.py
  
