name: Daily TQQQ Signal

on:
  schedule:
    - cron: "50 19 * * 1-5"  # 2:50 PM CT weekdays (approx. 19:50 UTC)
  workflow_dispatch:          # allows manual trigger

jobs:
  run-daily-signal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install yfinance scikit-learn joblib gspread oauth2client pandas numpy

      - name: Run daily signal script and email
        run: python tqqq_daily.py
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

  
