name: Daily TQQQ Signal

on:
  schedule:
    - cron: "0 12 * * 1-5"   # 8:00 AM ET weekdays
  workflow_dispatch:           # allows manual trigger

jobs:
  run-daily-signal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install yfinance scikit-learn joblib gspread oauth2client pandas numpy

      - name: Run daily signal script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python tqqq_daily.py

  
