name: Weekly TQQQ Retrain

on:
  schedule:
    - cron: "0 22 * * 0"   # 6:00 PM ET Sunday
  workflow_dispatch:

permissions:
  contents: write   # allow workflow to push updated model

jobs:
  run-retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install yfinance scikit-learn joblib gspread oauth2client pandas numpy

      - name: Run retrain script
        run: python tqqq_retrain.py
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
